name: playwright api and ui test
# Когда запускаем тесты
on:
  push:
    branches:
      - master
# Ручной запуск
  workflow_dispatch: 

jobs:
  pw5Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
      - name: Установка npm-пакеты из package.json
        run: npm ci
      - name: Установка браузеров
        run: npx playwright install --with-deps
      - name: Запусков тестов
        run: npm t
        # todo унести в package.json
      - name: Сгенерировать Allure 3 отчет в один файл 
        run: npx allure awesome ./allure-results --single-file
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Allure single file
          path: |
              allure-report/index.html
              allure-results
              playwright-report
